project_id = "qbtkhiotvhcpmuzawkhi"

[functions.delete-user]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.create-super-admin]
verify_jwt = false

[functions.manage-2fa]
verify_jwt = true

[functions.auto-backup]
verify_jwt = false

[functions.public-auth-settings]
verify_jwt = false

[functions.manage-financing-key]
verify_jwt = false
